-- Generated by scripts/schema.ts. Edit a migration, not this file.

table messages
  thread_id text not null
  message_id text not null
  seq bigint not null default nextval('messages_seq_seq'::regclass)
  body jsonb not null
  created_at timestamp with time zone not null default now()
  FOREIGN KEY (thread_id) REFERENCES threads(thread_id) ON DELETE CASCADE
  PRIMARY KEY (thread_id, message_id)
  CREATE INDEX messages_by_thread ON public.messages USING btree (thread_id, seq)

table sessions
  thread_id text not null
  entries jsonb not null
  updated_at timestamp with time zone not null default now()
  FOREIGN KEY (thread_id) REFERENCES threads(thread_id) ON DELETE CASCADE
  PRIMARY KEY (thread_id)

table threads
  thread_id text not null
  user_id text not null
  created_at timestamp with time zone not null default now()
  PRIMARY KEY (thread_id)
