/**
 * Writes `schema.txt`: what every committed migration adds up to.
 *
 * Read by whoever wants to know what a table looks like without replaying the migrations in
 * their head, and diffed by `check`, which is the part that catches a migration doing
 * something other than what its author believed.
 *
 * Built on a database made for the purpose and dropped afterwards. Dumping the development
 * database instead would put whatever else has ever been in it -- another branch's tables,
 * a hand-run experiment -- into a file this repository keeps.
 *
 * Not `pg_dump`, on purpose. This artefact is read and diffed, never restored, so it does
 * not have to be executable SQL -- and every awkward part of dumping is about making dump
 * output byte-identical: pinning the client's patch version because it stamps itself into
 * the file, fixing the random key it writes, running it inside the container so the versions
 * match. Asking the catalog instead is deterministic because we choose the order.
 */
import { SQL } from 'bun'
import { applyMigrations, databaseUrl } from './migrate'

/**
 * Not `.sql`, because it is not SQL and nobody should discover that by running it. Even a
 * dump that *was* valid SQL would be the wrong way to make a database: loading one leaves
 * `applied_migrations` empty, so the next migration run replays everything onto tables that
 * already exist. `bun run migrate` is the only way in.
 */
const HEADER = [
  'What the migrations in this checkout add up to.',
  '',
  'Generated by scripts/schema.ts. Edit a migration, not this file.',
  'This is a description, not SQL: to build a database, run `bun run migrate`.',
]
  .map((line) => (line === '' ? '#' : `# ${line}`))
  .join('\n')

const SCRATCH = 'vid_schema_only'
const OUTPUT = new URL('../schema.txt', import.meta.url).pathname

/** The runner's own bookkeeping is not part of our schema. */
const NOT_OURS = 'applied_migrations'

type Column = {
  table_name: string
  column_name: string
  data_type: string
  is_nullable: string
  column_default: string | null
}

const describe = async (sql: SQL): Promise<string> => {
  const columns: Column[] = await sql`
    select table_name, column_name, data_type, is_nullable, column_default
    from information_schema.columns
    where table_schema = 'public' and table_name <> ${NOT_OURS}
    order by table_name, ordinal_position
  `

  const constraints: { table_name: string; name: string; definition: string }[] = await sql`
    select rel.relname as table_name, con.conname as name,
           pg_get_constraintdef(con.oid) as definition
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
    where nsp.nspname = 'public' and rel.relname <> ${NOT_OURS}
    order by rel.relname, pg_get_constraintdef(con.oid)
  `

  // A primary key and a unique constraint each come with an index of the same name. Listing
  // both says one thing twice, and the second one reads like a decision someone made.
  const implied = new Set(constraints.map((constraint) => constraint.name))

  const indexes: { tablename: string; indexdef: string }[] = await sql`
    select tablename, indexdef from pg_indexes
    where schemaname = 'public' and tablename <> ${NOT_OURS}
    order by tablename, indexdef
  `

  const tables = [...new Set(columns.map((column) => column.table_name))]

  const blocks = tables.map((table) => {
    const mine = columns.filter((column) => column.table_name === table)
    const width = Math.max(...mine.map((column) => column.column_name.length))

    const body = mine
      .map((column) => `    ${column.column_name.padEnd(width)}  ${shape(column)}`)
      .join('\n')

    // Constraint and index definitions are quoted from Postgres rather than rewritten.
    // Reformatting them would mean parsing check constraints and expression indexes, and
    // the first one misread is a schema this file describes wrongly.
    const rules = section(
      'constraints',
      constraints.filter((constraint) => constraint.table_name === table).map((c) => c.definition),
    )

    const keys = section(
      'indexes',
      indexes
        .filter((index) => index.tablename === table && !implied.has(nameOf(index.indexdef)))
        .map((index) => index.indexdef),
    )

    return [`table ${table}`, '  columns', body, rules, keys]
      .filter((part) => part !== '')
      .join('\n')
  })

  return `${[HEADER, ...blocks].join('\n\n')}\n`
}

const section = (label: string, lines: readonly string[]): string =>
  lines.length === 0 ? '' : [`  ${label}`, ...lines.map((line) => `    ${line}`)].join('\n')

/** `CREATE [UNIQUE] INDEX <name> ON ...` -- the third word. */
const nameOf = (definition: string): string =>
  definition.split(' ').at(definition.startsWith('CREATE UNIQUE') ? 3 : 2) ?? ''

const shape = (column: Column): string => {
  const parts = [column.data_type]
  if (column.is_nullable === 'NO') parts.push('not null')
  if (column.column_default !== null) parts.push(`default ${column.column_default}`)
  return parts.join(' ')
}

const url = databaseUrl()

const server = new SQL(url.replace(/\/[^/]*$/, '/postgres'))
await server`drop database if exists ${server(SCRATCH)}`
await server`create database ${server(SCRATCH)}`

const scratch = new SQL(url.replace(/\/[^/]*$/, `/${SCRATCH}`))
await applyMigrations(scratch)
await Bun.write(OUTPUT, await describe(scratch))
await scratch.close()

await server`drop database if exists ${server(SCRATCH)}`
await server.close()

console.log(`wrote ${OUTPUT}`)
